### ISSUE TITLE
Bugs in beginProgMotorShield, beginProgPololu

### ISSUE THREAD

**Issue by cescp** [Locoduino/DCCpp#2]
Hi,
I think that code in DCCpp.hpp has two bugs: 
- definition of beginProgMotorShield() should call beginProg instead of beginMain
- definition of beginProgPololu() should call beginProg instead of beginMain

I've tried with an Arduino Motor Shield v3, and programming track (B) only works if beginProgMotorShield calls beginProg.

**Comment by Trusty77** [comment]
Hi,

Thanks you for your interest. I will fix it soon by a new version.

**Comment by Trusty77** [comment]
Fixed in 1.3.2
