### ISSUE TITLE
Use only one timer to bitbang DCC

### ISSUE THREAD

**Issue by positron96** [Locoduino/DCCpp#3]
Hello!
I noticed that the project (as well as DCC++) uses 6 pins for DCC generation when in fact only 4 are needed for the motor shield. This is caused by usage of compare registers (as I remember) that disable usage of two extra pins. Also, 2 timers are used to control 2 tracks.

What I propose is to use only one timer (timer2 on atmega328) and digitalWrite-esque code inside timer ISR to control DCC signals on both tracks. 
This allows to use any pins to connect to motor shield and frees one timer to do something else.

I've tested my code on Arduino Nano with L298 board and it works correctly. My changes are, however, made to DCC++ project (not DCCpp), which has not been modified for 4 years, therefore I propose a change here. I can try to port them to DCCpp if anyone is interested.

**Comment by Trusty77** [comment]
Hello
This is a very good idea. The only condition is to be able to still use the old motor shields, so perhaps the two ways should be available through a #define ...

**Comment by positron96** [comment]
Yes, existing shields will be able to be used. They will no longer need adding jumper wires between pins driven by compare registers and shield input pins, which I consider an improvement.

**Comment by Trusty77** [comment]
Issue covered.
