### ISSUE TITLE
IDE 1.8.13, can't compile examples

### ISSUE THREAD

**Issue by lucadentella** [Locoduino/DCCpp#7]
Hi!

I'm trying to compile the provided examples (starting from MiniDcc) on IDE 1.8.13 but I get some errors:

`libraries\DCCpp\src\Locomotives\Registers.cpp:10:27: error: 'MAXIMUM_REGISTER_SIZE' was not declared in this scope
 byte Registers::registers[MAXIMUM_REGISTER_SIZE / 8];`

For each cpp file in \Locomotives subfolder I had to manually #import the corresponding hpp file to make it works... 
Is it a recent change in how the compiler/linker work? 

Thanks

**Comment by lucadentella** [comment]
In addition, if I completely remove the \Locomotives subfolder, it seems to work... I installed the library through Arduino's library manager, don't know if it makes some difference

**Comment by Trusty77** [comment]
Hi,

I have removed these files from the version since the 4 april. Have you used the last version ?

Otherwise, just delete the Locomotives folder.
Thierry Paris

**Comment by lucadentella** [comment]
Hi! I installed the library from Arduino Library Manager and it downloaded the version with that folder inside.

If you check your library.properties it points to tag 1.4.1 (https://github.com/Locoduino/DCCpp/releases/tag/v1.4.1), maybe it should be updated to match the latest tag which doesn't contain the folder anymore.

Thanks for your support
